// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwey5pEQz8FhLtRBlSepEMYz2UfnRHsKw',
    appId: '1:1008606336713:web:cc6f7e279ab5b323ca9f18',
    messagingSenderId: '1008606336713',
    projectId: 'chat-app-pgdm',
    authDomain: 'chat-app-pgdm.firebaseapp.com',
    storageBucket: 'chat-app-pgdm.firebasestorage.app',
    measurementId: 'G-28RN7Q1T3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTXVJ7vBVEdeGdqy4w0Z2lno7BfJTeImI',
    appId: '1:1008606336713:android:23d005f7e5c242b4ca9f18',
    messagingSenderId: '1008606336713',
    projectId: 'chat-app-pgdm',
    storageBucket: 'chat-app-pgdm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8JDjzXv0ReSVx3fJIQdlvEWMs6QvgLcM',
    appId: '1:1008606336713:ios:de3eef298229fcb0ca9f18',
    messagingSenderId: '1008606336713',
    projectId: 'chat-app-pgdm',
    storageBucket: 'chat-app-pgdm.firebasestorage.app',
    iosBundleId: 'br.edu.ifsp.aluno.chatAppPgdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8JDjzXv0ReSVx3fJIQdlvEWMs6QvgLcM',
    appId: '1:1008606336713:ios:de3eef298229fcb0ca9f18',
    messagingSenderId: '1008606336713',
    projectId: 'chat-app-pgdm',
    storageBucket: 'chat-app-pgdm.firebasestorage.app',
    iosBundleId: 'br.edu.ifsp.aluno.chatAppPgdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwey5pEQz8FhLtRBlSepEMYz2UfnRHsKw',
    appId: '1:1008606336713:web:89bafef718d8d7beca9f18',
    messagingSenderId: '1008606336713',
    projectId: 'chat-app-pgdm',
    authDomain: 'chat-app-pgdm.firebaseapp.com',
    storageBucket: 'chat-app-pgdm.firebasestorage.app',
    measurementId: 'G-LR8PHCY0ZZ',
  );
}
